# general settings
name: train_LSM_light_lightSR_x4_finetune
model_type: LSMModel
scale: 4
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: ./datasets/DIV2K/HR
    dataroot_lq: ./datasets/DIV2K/LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 384
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 16
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    task: SR
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: ./datasets/SR/Urban100/HR
    dataroot_lq: ./datasets/SR/Urban100/LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

# network structures
network_g:
  type: LSM_light
  upscale: 4
  in_chans: 3
  img_size: 96
  d_state: 16
  img_range: 1.
  depth: [6,6,6,6]
  embed_dim: 60
  num_heads: [4,4,4,4]
  mlp_ratio: 1.0
  resi_connection: '1conv'
  split_size: [8,32]
  rmin: 0.9
  rmax: 0.99
  max_phase: 6.283
  num_tokens: 64

# path
path:
  pretrain_network_g: ./experiments/train_LSM_light_lightSR_x2_finetune/models/net_g_best.pth  # ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.9]


  scheduler:
    type: MultiStepLR
    milestones: [125000, 200000, 225000, 237500]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: 10000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500